INSERT INTO ARTIST (FIRST_NAME,LAST_NAME) VALUES ('Jennifer', 'Lopez');
INSERT INTO ARTIST (FIRST_NAME,LAST_NAME) VALUES ('Pink', 'Floyd');
INSERT INTO ARTIST (FIRST_NAME,LAST_NAME) VALUES ('Taylor', 'Swift');

INSERT INTO TRACK (DURATION_IN_MINUTES,ALBUM, ISSUE_DATE,TITLE,TYPE) VALUES (3.4, 'The Tortured Poets', '2024-04-19', 'Fortnight', 'MP3');
INSERT INTO TRACK (DURATION_IN_MINUTES,ALBUM, ISSUE_DATE,TITLE,TYPE) VALUES (3.24, 'The Tortured Poets', '2024-04-19', 'My Boy Only Breaks', 'MP3');
INSERT INTO TRACK (DURATION_IN_MINUTES,ALBUM, ISSUE_DATE,TITLE,TYPE) VALUES (4.21, 'The Tortured Poets', '2024-04-19', 'Down Bad', 'MP3');

INSERT INTO TRACK_ARTIST (ARTIST_ID, TRACK_ID) VALUES (3,1);
INSERT INTO TRACK_ARTIST (ARTIST_ID, TRACK_ID) VALUES (3,2);
INSERT INTO TRACK_ARTIST (ARTIST_ID, TRACK_ID) VALUES (3,3);


