services:
  trackservice:
    container_name: trackservice
    image: track-image
    build: .
    ports:
      - 8000:8000
    environment:
      - CREDENTIALS=${CREDENTIALS}
    depends_on:
      - priceservice
  priceservice:
    container_name: priceservice
    image: price-image
    build: ../pricingservice/.
    ports:
      - 10002:10002