INSERT INTO ARTIST (FIRST_NAME,LAST_NAME) VALUES ('Jennifer', 'Lopez');
INSERT INTO ARTIST (FIRST_NAME,LAST_NAME) VALUES ('Pink', 'Floyd');
INSERT INTO ARTIST (FIRST_NAME,LAST_NAME) VALUES ('Taylor', 'Swift');

INSERT INTO TRACK (DURATION_IN_MINUTES,ALBUM, ISSUE_DATE,TITLE,TYPE) VALUES (1.4, 'The Tortured Poets', '2023-04-19', 'Fortnight', 'MP3');
INSERT INTO TRACK (DURATION_IN_MINUTES,ALBUM, ISSUE_DATE,TITLE,TYPE) VALUES (2, 'The Tortured Poets', '2024-04-19', 'My Boy Only Breaks', 'OGG');
INSERT INTO TRACK (DURATION_IN_MINUTES,ALBUM, ISSUE_DATE,TITLE,TYPE) VALUES (4.21, 'The Tortured Poets', '2024-04-19', 'Down Bad', 'OGG');

INSERT INTO TRACK_ARTIST (ARTIST_ID, TRACK_ID) VALUES (3,1);
INSERT INTO TRACK_ARTIST (ARTIST_ID, TRACK_ID) VALUES (2,1);
INSERT INTO TRACK_ARTIST (ARTIST_ID, TRACK_ID) VALUES (1,3);


